### PR TITLE
Jin hui

### PR DESCRIPTION
**Pull request by JinHui-oss**
added test case for fail and pass, acceptance is ongoing.

### CODE REVIEW

**Comment by DandaIT04** [comment]
i fixed the conflicts your settings was having

**Comment by JinHui-oss** [comment]
okay

**Comment by JinHui-oss** [comment]
re-run the action or?

**Comment by DandaIT04** [comment]
did you add all the test cases? did you test each test cases? If it fails, it won't run. Did you also add some into my match stud test case?

**Comment by JinHui-oss** [comment]
there are two case suppose to be fail test case so do i remove it?

**Comment by JinHui-oss** [comment]
I tested all the test case 3 pass and 2 fail

**Comment by DandaIT04** [comment]
remove the failed ones.

**Comment by JinHui-oss** [comment]
removed now waiting

**Comment by DandaIT04** [comment]
looks ok

**Comment by DandaIT04** [comment]
I will merge once the checks are successful, thanks

**Comment by joostinn** [comment]
Ok looks good

**Pull request merged**
